[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cobra-array"
dynamic = ["version"]
description = "A backend-agnostic array utility library that unifies array conversion, context control, and cross-library operations across `NumPy`/`PyTorch`-style ecosystems."
readme = "README.md"
license-files = ["LICENSE"]
authors = [
    {name = "Zhen Tian", email = "zhen.tian.cs@gmail.com"}
]
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
    "array-api-compat>=1.11.2"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "numpy>=1.21,<2.0",
    "torch>=1.10,<2.0",
]

[project.urls]
Homepage = "https://github.com/tinchen777/cobra-array.git"
Repository = "https://github.com/tinchen777/cobra-array.git"
Issues = "https://github.com/tinchen777/cobra-array.git/issues"

[tool.setuptools.dynamic]
version = {attr = "cobra_array.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["cobra_array*"]
