# src/cobra_array/result.py
# -*- coding: utf-8 -*-
# Python version: 3.9
# @TianZhen

from 
from typing import (List, Optional, Any, Iterable, Sequence, TYPE_CHECKING)


import torch
from numpy.typing import NDArray
from array_api_compat.common._typing import Namespace


from .types import DeviceT


Axis = int | tuple[int, ...] | None
Shape = int | tuple[int, ...]
ArrayLikeOrScalar = Any
DType = Any
Device = Any


class CompatArray:
    def __init__(self, arr: object, /): ...

    def to_numpy(self, copy: bool = False) -> NDArray[Any]:
        """
        Convert the array to a `NumPy array`.
        """
        ...

    def to_tensor(
        self,
        device: Optional[DeviceT] = None,
        copy: bool = False
    ) -> torch.Tensor:
        """
        Convert the array to a `PyTorch tensor`.
        """
        ...

    def to_list(self, copy: bool = False) -> List[Any]:
        """
        Convert the array to a built-in `list`.
        """
        ...

    @property
    def arr(self):
        """
        The original array.
        """
        ...

    @property
    def xp(self) -> Namespace:
        """
        The array namespace of the original array.
        """
        ...
    
    
    
    
    @property
    def dtype(self) -> DType: ...
    @property
    def device(self) -> Device: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...

    def __array__(self, dtype: Any = ..., /) -> Any: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __index__(self) -> int: ...

    def __getitem__(self, key: Any, /) -> "ArrayLike": ...
    def __setitem__(self, key: Any, value: Any, /) -> None: ...

    def __neg__(self) -> "ArrayLike": ...
    def __pos__(self) -> "ArrayLike": ...
    def __invert__(self) -> "ArrayLike": ...

    def __add__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __radd__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __sub__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rsub__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __mul__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rmul__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __truediv__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rtruediv__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __floordiv__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rfloordiv__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __mod__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rmod__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __pow__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rpow__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __matmul__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rmatmul__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...

    def __and__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rand__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __or__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __ror__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __xor__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rxor__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __lshift__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rlshift__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rshift__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __rrshift__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...

    def __eq__(self, other: object, /) -> "ArrayLike": ...
    def __ne__(self, other: object, /) -> "ArrayLike": ...
    def __lt__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __le__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __gt__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def __ge__(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...

    def astype(self, dtype: DType, /, *, copy: bool = ...) -> "ArrayLike": ...
    def copy(self) -> "ArrayLike": ...

    def reshape(self, shape: Shape, /) -> "ArrayLike": ...
    def flatten(self) -> "ArrayLike": ...
    def squeeze(self, axis: int | tuple[int, ...] | None = ..., /) -> "ArrayLike": ...
    def expand_dims(self, axis: int, /) -> "ArrayLike": ...
    def permute_dims(self, axes: tuple[int, ...], /) -> "ArrayLike": ...
    def transpose(self, axes: tuple[int, ...] | None = ..., /) -> "ArrayLike": ...
    def broadcast_to(self, shape: tuple[int, ...], /) -> "ArrayLike": ...
    def flip(self, axis: int | tuple[int, ...] | None = ..., /) -> "ArrayLike": ...
    def roll(self, shift: int | Sequence[int], axis: int | Sequence[int] | None = ..., /) -> "ArrayLike": ...
    def repeat(self, repeats: int, axis: int | None = ..., /) -> "ArrayLike": ...
    def tile(self, repetitions: int | Sequence[int], /) -> "ArrayLike": ...

    def sum(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def prod(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def mean(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def std(self, /, *, axis: Axis = ..., correction: float = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def var(self, /, *, axis: Axis = ..., correction: float = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def max(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def min(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def all(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def any(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...

    def argmax(self, /, *, axis: int | None = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def argmin(self, /, *, axis: int | None = ..., keepdims: bool = ...) -> "ArrayLike": ...
    def nonzero(self) -> tuple["ArrayLike", ...]: ...
    def count_nonzero(self, /, *, axis: Axis = ..., keepdims: bool = ...) -> "ArrayLike": ...

    def sort(self, /, *, axis: int = ..., descending: bool = ...) -> "ArrayLike": ...
    def argsort(self, /, *, axis: int = ..., descending: bool = ...) -> "ArrayLike": ...

    def abs(self) -> "ArrayLike": ...
    def negative(self) -> "ArrayLike": ...
    def positive(self) -> "ArrayLike": ...
    def sign(self) -> "ArrayLike": ...
    def signbit(self) -> "ArrayLike": ...
    def square(self) -> "ArrayLike": ...
    def sqrt(self) -> "ArrayLike": ...
    def reciprocal(self) -> "ArrayLike": ...

    def exp(self) -> "ArrayLike": ...
    def expm1(self) -> "ArrayLike": ...
    def log(self) -> "ArrayLike": ...
    def log1p(self) -> "ArrayLike": ...
    def log2(self) -> "ArrayLike": ...
    def log10(self) -> "ArrayLike": ...

    def sin(self) -> "ArrayLike": ...
    def cos(self) -> "ArrayLike": ...
    def tan(self) -> "ArrayLike": ...
    def asin(self) -> "ArrayLike": ...
    def acos(self) -> "ArrayLike": ...
    def atan(self) -> "ArrayLike": ...
    def sinh(self) -> "ArrayLike": ...
    def cosh(self) -> "ArrayLike": ...
    def tanh(self) -> "ArrayLike": ...
    def asinh(self) -> "ArrayLike": ...
    def acosh(self) -> "ArrayLike": ...
    def atanh(self) -> "ArrayLike": ...

    def ceil(self) -> "ArrayLike": ...
    def floor(self) -> "ArrayLike": ...
    def trunc(self) -> "ArrayLike": ...
    def round(self) -> "ArrayLike": ...

    def real(self) -> "ArrayLike": ...
    def imag(self) -> "ArrayLike": ...
    def conj(self) -> "ArrayLike": ...

    def clip(self, min: ArrayLikeOrScalar | None = ..., max: ArrayLikeOrScalar | None = ..., /) -> "ArrayLike": ...

    def equal(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def not_equal(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def less(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def less_equal(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def greater(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def greater_equal(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...

    def logical_and(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def logical_or(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def logical_xor(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def logical_not(self) -> "ArrayLike": ...

    def bitwise_and(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def bitwise_or(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def bitwise_xor(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def bitwise_left_shift(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def bitwise_right_shift(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def bitwise_invert(self) -> "ArrayLike": ...

    def isfinite(self) -> "ArrayLike": ...
    def isinf(self) -> "ArrayLike": ...
    def isnan(self) -> "ArrayLike": ...

    def cumulative_sum(self, /, *, axis: int | None = ..., include_initial: bool = ...) -> "ArrayLike": ...

    def matmul(self, other: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def matrix_transpose(self) -> "ArrayLike": ...
    def vecdot(self, other: ArrayLikeOrScalar, /, *, axis: int = ...) -> "ArrayLike": ...

    def where(self, x1: ArrayLikeOrScalar, x2: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    def take(self, indices: ArrayLikeOrScalar, /, *, axis: int | None = ...) -> "ArrayLike": ...

    def unique_values(self) -> "ArrayLike": ...
    def unique_counts(self) -> Any: ...
    def unique_inverse(self) -> Any: ...
    def unique_all(self) -> Any: ...

    def to_device(self, device: Device, /, *, stream: Any = ...) -> "ArrayLike": ...
    def tolist(self) -> list[Any]: ...
    def item(self) -> Any: ...

    @classmethod
    def asarray(
        cls,
        obj: Any,
        /,
        *,
        dtype: DType | None = ...,
        device: Device | None = ...,
        copy: bool | None = ...
    ) -> "ArrayLike": ...

    @classmethod
    def arange(
        cls,
        start: Any,
        /,
        stop: Any | None = ...,
        step: Any = ...,
        *,
        dtype: DType | None = ...,
        device: Device | None = ...
    ) -> "ArrayLike": ...

    @classmethod
    def zeros(
        cls,
        shape: Shape,
        /,
        *,
        dtype: DType | None = ...,
        device: Device | None = ...
    ) -> "ArrayLike": ...

    @classmethod
    def ones(
        cls,
        shape: Shape,
        /,
        *,
        dtype: DType | None = ...,
        device: Device | None = ...
    ) -> "ArrayLike": ...

    @classmethod
    def full(
        cls,
        shape: Shape,
        fill_value: Any,
        /,
        *,
        dtype: DType | None = ...,
        device: Device | None = ...
    ) -> "ArrayLike": ...

    @classmethod
    def empty(
        cls,
        shape: Shape,
        /,
        *,
        dtype: DType | None = ...,
        device: Device | None = ...
    ) -> "ArrayLike": ...

    @classmethod
    def eye(
        cls,
        n_rows: int,
        n_cols: int | None = ...,
        /,
        *,
        k: int = ...,
        dtype: DType | None = ...,
        device: Device | None = ...
    ) -> "ArrayLike": ...

    @classmethod
    def linspace(
        cls,
        start: Any,
        stop: Any,
        /,
        *,
        num: int,
        dtype: DType | None = ...,
        device: Device | None = ...,
        endpoint: bool = ...
    ) -> "ArrayLike": ...

    @classmethod
    def concat(cls, arrays: Iterable[ArrayLikeOrScalar], /, *, axis: int | None = ...) -> "ArrayLike": ...
    @classmethod
    def stack(cls, arrays: Iterable[ArrayLikeOrScalar], /, *, axis: int = ...) -> "ArrayLike": ...
    @classmethod
    def where_cls(cls, condition: ArrayLikeOrScalar, x1: ArrayLikeOrScalar, x2: ArrayLikeOrScalar, /) -> "ArrayLike": ...
    @classmethod
    def matmul_cls(cls, x1: ArrayLikeOrScalar, x2: ArrayLikeOrScalar, /) -> "ArrayLike": ...
