# src/cobra_array/convert.py
# -*- coding: utf-8 -*-
# Python version: 3.9
# @TianZhen

from __future__ import annotations
from numpy.typing import NDArray
from torch import Tensor
from array_api_compat.common._typing import Namespace
from typing import (Any, Literal, Optional, List, Iterable, Union, overload)

from .types import (
    T, StringT,
    DTypeT, dtypeT, DType, AnyDevice,
    ArrayLike, ArrayLibraryName
)


@overload
def to_numpy(obj: NDArray[dtypeT], /, *, dtype: None = ..., copy: bool = ...) -> NDArray[dtypeT]: ...
@overload
def to_numpy(obj: ArrayLike[dtypeT], /, *, dtype: None = ..., copy: bool = ...) -> NDArray[dtypeT]: ...
@overload
def to_numpy(obj: object, /, *, dtype: None = ..., copy: bool = ...) -> NDArray[Any]: ...
@overload
def to_numpy(obj: object, /, *, dtype: DTypeT, copy: bool = ...) -> NDArray[DTypeT]: ...
def to_numpy(obj: object, /, *, dtype: Optional[DType] = None, copy: bool = True) -> NDArray[Any]: ...


def to_tensor(obj: object, /, *, dtype: Optional[DType] = None, device: Optional[AnyDevice] = None, copy: bool = True) -> Tensor: ...


@overload
def to_list(obj: List[T], /, *, copy: bool = ...) -> List[T]: ...
@overload
def to_list(obj: StringT, /, *, copy: bool = ...) -> List[StringT]: ...
@overload
def to_list(obj: NDArray[dtypeT], /, *, copy: bool = ...) -> List[dtypeT]: ...
@overload
def to_list(obj: ArrayLike[dtypeT], /, *, copy: bool = ...) -> List[dtypeT]: ...
@overload
def to_list(obj: Iterable[T], /, *, copy: bool = ...) -> List[T]: ...
@overload
def to_list(obj: T, /, *, copy: bool = ...) -> List[T]: ...
@overload
def to_list(obj: object, /, *, copy: bool = ...) -> List[Any]: ...
def to_list(obj: object, /, *, copy: bool = True) -> List[Any]: ...


def to_xp(obj: Union[object, ArrayLibraryName], /) -> Namespace: ...


@overload
def as_array(obj: NDArray[dtypeT], xp: Literal["numpy"], /, *, dtype: None = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: bool = ...) -> NDArray[dtypeT]: ...
@overload
def as_array(obj: ArrayLike[dtypeT], xp: Literal["numpy"], /, *, dtype: None = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: bool = ...) -> NDArray[dtypeT]: ...
@overload
def as_array(obj: object, xp: Literal["numpy"], /, *, dtype: None = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: Literal[False] = ...) -> NDArray[Any]: ...
@overload
def as_array(obj: object, xp: Literal["numpy"], /, *, dtype: DTypeT, device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: Literal[False] = ...) -> NDArray[DTypeT]: ...
@overload
def as_array(obj: object, xp: Literal["torch"], /, *, dtype: Optional[DType] = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: Literal[False] = ...) -> Tensor: ...
@overload
def as_array(obj: NDArray[dtypeT], xp: Union[object, ArrayLibraryName], /, *, dtype: None = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: bool = ...) -> ArrayLike[dtypeT]: ...
@overload
def as_array(obj: ArrayLike[dtypeT], xp: Union[object, ArrayLibraryName], /, *, dtype: None = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: bool = ...) -> ArrayLike[dtypeT]: ...
@overload
def as_array(obj: object, xp: Union[object, ArrayLibraryName], /, *, dtype: None = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: Literal[False] = ...) -> ArrayLike[Any]: ...
@overload
def as_array(obj: object, xp: Union[object, ArrayLibraryName], /, *, dtype: DTypeT, device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: Literal[False] = ...) -> ArrayLike[DTypeT]: ...
@overload
def as_array(obj: T, xp: Union[object, ArrayLibraryName], /, *, dtype: Optional[DType] = ..., device: Optional[AnyDevice] = ..., copy: bool = ..., arraylike_only: Literal[True]) -> T: ...
def as_array(obj: object, xp: Union[object, ArrayLibraryName], /, *, dtype: Optional[DType] = None, device: Optional[AnyDevice] = None, copy: bool = False, arraylike_only: bool = False) -> Any: ...
